name: flutter_feathersjs
description: Communicate with you feathers js server from flutter.
version: 0.0.1-dev
homepage: https://github.com/Dahkenangnon/flutter_feathersjs.dart
repository: https://github.com/Dahkenangnon/flutter_feathersjs.dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Socketio client
  socket_io_client: ^0.9.9
  # Http client
  dio: ^3.0.9
  # For storing the acces token
  sembast: ^2.4.7+7
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
