name: flutter_feathersjs
description: Communicate with your feathers js  server from flutter app with unbelieved ease and make happy your customers.
version: 4.1.1-dev
homepage: https://github.com/Dahkenangnon/flutter_feathersjs.dart
repository: https://github.com/Dahkenangnon/flutter_feathersjs.dart
documentation: https://dahkenangnon.github.io/flutter_feathersjs.dart/
issue_tracker: https://github.com/Dahkenangnon/flutter_feathersjs.dart/issues


environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Used for socket connection
  socket_io_client: ^1.0.2

  # Used for http connection
  dio: ^4.0.6

  # Used for secure storage on device
  flutter_secure_storage: ^6.0.0

  # Emit events
  event_bus: ^2.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
